<?php

/**
 * @file
 * Include file for ingest related functions.
 */

/*
 * TODO: write functions that will make the drush commands for ingest of each 
 *       model type based on configuration. 
 * 
 * TODO: write function to call a drush command -- and log that command in a
 *       new table `islandora_digital_workflow_drush_log` (drush_log_id, 
 *         batch_id, batch_item_id, drupal_uid, drush_command, output, 
 *         return_val, timestamp).
 *
 */
